### PR TITLE
Add support for PCRE

### PR DESCRIPTION
**Pull request by shadialtarsha**
Why?
Falco ([the go regexp pkg](https://pkg.go.dev/regexp) to be more accurate!) right now doesn't know how to parse [PCRE](https://www.pcre.org/) regular expressions that Varnish uses.
An example of that would be this file:
https://github.com/varnishcache/varnish-devicedetect/blob/master/devicedetect.vcl

**Edit1:** 
I created a small repo that uses [ccgo](https://modernc.org/ccgo/v3) compiler to translate the PCRE2 source code to Go.
https://github.com/shadialtarsha/go-pcre

Would love to hear your opinion about this

**Edit2:** 
CI is green. I added a build step for `pullrequest.yaml` and it passed, then I removed it.

### CODE REVIEW

**Comment by shadialtarsha** [comment]
@ysugimoto and @davinci26 would like to hear your opinion and get a review for this PR.

**Comment by shadialtarsha** [comment]
Also @ivomurrell would like to hear your thoughts about this PR as you are a very active contributor of this repo 😬

**Comment by ysugimoto** [comment]
@shadialtarsha 

We'll aim to release cross-platform binary from CI.
Your fork repository of https://github.com/shadialtarsha/go-pcre looks neat to support macos arm64 and we only need to compile each platform binaries on GitHub Actions runner.

Unfortunately, GitHub Actions does not support macos arm64 platform for now: https://github.com/actions/runner-images/issues/2187 so This PR is still blocked until we can make arm64 binary on GitHub Actions runner.

**Comment by shadialtarsha** [comment]
Hey @ysugimoto 
This PR eliminates the dependency on any OS or Arch! That is the whole idea of my repo https://github.com/shadialtarsha/go-pcre 😄 
My repo provides a cgo-free alternative to what I proposed at the beginning. 
So tl;dr the CI will work as expected and as it is before nothing has changed.

**Comment by ysugimoto** [comment]
@shadialtarsha 
Good work, but I tried to compile linux binary on M1 mac, and the compilation failed:

```
# runtime/cgo
linux_syscall.c:67:13: error: implicit declaration of function 'setresgid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:67:13: note: did you mean 'setregid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:593:6: note: 'setregid' declared here
linux_syscall.c:73:13: error: implicit declaration of function 'setresuid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:73:13: note: did you mean 'setreuid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:595:6: note: 'setreuid' declared here
make: *** [linux] Error 2
```

And the [GitHub Actions on this PR](https://github.com/ysugimoto/falco/runs/8178038516?check_suite_focus=true) seems to pass only the test and lint, we aim to build for each OS/Arch binaries from CI. Did you try that?
I'm guessing that the GitHub Action runs on Ubuntu so the compile binary for macos/arm64 will fail.

**Comment by davinci26** [comment]
I am confused because the CI is passing here https://github.com/ysugimoto/falco/pull/90/commits/63bfba79fa85449ab89bd4562d1e3b43608473d7

**Review by davinci26 — APPROVED** [review]

**Comment by shadialtarsha** [comment]
I created a PR that tests the` build` step in github actions
https://github.com/ysugimoto/falco/pull/103

Looks good:https://github.com/ysugimoto/falco/actions/runs/3069169999/jobs/4957501750

**Comment by shadialtarsha** [comment]
Also @ysugimoto I have an M1 machine and I did `make linux` and I got a binary from it! 
Wondering what steps to reproduce the error above?

**Comment by ysugimoto** [comment]
@shadialtarsha Ah, sorry for forgetting to release.
Some other PRs are merged into `main` so let's release this after them.

1. release next _minor_ version from `main` branch
2. merge this PR and release _minor_ branch

**Pull request merged**
